[JDBC 라이브러리] 철시 미션 제출합니다.
woowacourse/jwp-jdbc pull request #16
Opened 2019-10-16 03:02 UTC by pkch93

안녕하세요 구구! 이번 JDBC 라이브러리 리뷰 부탁 드리게 된 철시입니다 ㅎㅎ

저번 level2에서도 한 번 받았었는데 다시 만나게 됬네요 :) 이번에도 잘 부탁드립니다!

2019-10-16 13:18 UTC, kang-hyungu requested changes
안녕하세요 철시님!
미션 구현 잘 하셨어요 👍 
jdbc 프레임워크 사용자가 더 편하게 쓸 수 있도록 개선하면 좋을 부분에 코멘트 남겼어요
확인해보시고 수정해보세요!

2019-10-16 13:18 UTC, kang-hyungu commented on slipp/src/main/java/slipp/dao/UserDao.java
> +            try {
jdbc template을 사용자 입장에서 매번 쿼리마다 try catch를 작성해야 된다면 불편하지 않을까요?
jdbc 프레임워크에서 try catch를 처리하도록 변경해보아요

2019-10-16 13:18 UTC, kang-hyungu commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        PreparedStatementSetter pss = pstmt -> {
불필요한 변수는 선언하지 않아도 전체 조회 가능하도록 기능 추가를 해보세요!

2019-10-16 13:18 UTC, kang-hyungu commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            pss.setValues(pstmt);
https://github.com/woowacourse/jwp-jdbc/pull/16/files#diff-ce2d167df205733db9660064c5b2e431R33
이 메서드와 26번째 줄을 제외하면 중복된 코드 아닐까요?
중복을 제거해보세요!

2019-10-16 13:18 UTC, kang-hyungu commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public List<T> query(String sql, RowMapper<T> rowMapper, PreparedStatementSetter pss) {
query, queryForObject에서도 중복 코드가 보이네요
중복을 제거해보세요!

2019-10-17 05:55 UTC, pkch93 commented on slipp/src/main/java/slipp/dao/UserDao.java
> +            try {
프레임워크를 개발하고 있다는 것을 간과했네요 ㅠ 좋은 피드백 감사합니다!

2019-10-17 05:55 UTC, pkch93 commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        PreparedStatementSetter pss = pstmt -> {
queryAll 메서드를 jdbcTemplate에 추가하여 전체 조회 할 수 있도록 만들었습니다!

2019-10-17 05:56 UTC, pkch93 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            pss.setValues(pstmt);
파라미터로 받은 values를 PreparedStatementSetter로 변환하여 PreparedStatementSetter를 인자로 받는 메서드를 호출하도록 변경하였습니다 :)

2019-10-17 06:34 UTC, pkch93 commented
좋은 피드백 감사합니다 :)
피드백 반영하면서 추가로 변경하면 좋겠다는 부분을 다음과 같이 반영했습니다.

1. JdbcTemplate 클래스를 제네릭 클래스로 선언했었는데 JdbcTemplate 각 메서드를 제네릭 메서드로 변경했습니다.

Dao 단에서 하나의 로직에도 다양한 Object를 DB에 반영할 수도 있을 것 같다는 생각과 이 경우 각 클래스에 맞는 JdbcTemplate을 각각 생성해줘야하는 문제점이 있다고 판단하여 제네릭 클래스가 아닌 메서드 제네릭으로 변경하였습니다 :)

2. queryForObject에서 결과가 한 개 이상인 경우는 에러를 내뿜지만 결과가 없는 경우는 처리하지 않아 이 부분도 예외가 발생하도록 처리하였습니다.

감사합니다 :)

2019-10-17 11:46 UTC, kang-hyungu approved these changes
피드백 반영 잘 하셨어요! 👏 
특별히 추가 코멘트 남길 부분은 없네요.
머지 처리할게요 수고하셨습니다!

2019-10-17 11:46 UTC, merged