[JDBC 라이브러리] 마틴 미션 제출합니다.
woowacourse/jwp-jdbc pull request #21
Opened 2019-10-16 09:15 UTC by oeeen

안녕하세요! 리뷰어님!

## 질문
JdbcTemplate 구현 하면서, 두 가지 방식으로 해주었는데요.

1. reflection을 사용해서 내부에서 ResultSet으로 객체를 만들어 주는 것
  - `public <T> List<T> query(String query, Class<?> clazz, Object... objects)`
2. UserDao에서 RowMapper의 mapRow()를 구현방법을 받아서 객체 생성 하는 것
  - `public <T> List<T> query(String query, RowMapper rowMapper, Object... objects)`

두 가지 방식 중 한 가지씩 주석처리 해두었고 코드는 살려두었습니다. 

2번 방법인 UserDao에서 객체의 매핑 방식을 정해주는 것도 옳은 것 같지만, 

1번 방법인 클래스 타입만 정해서 넘겨주면 그 클래스에 해당하는 필드를 채워서 리턴해주는 것도 jdbcTemplate 사용자 입장에서는 좀더 편한 방식이라고 생각되어 어떤 것이 옳은지 잘 모르겠어서 질문드립니다!

## 참고 사항
그리고 또 JdbcTemplate 코드에서 트랜잭션 관리를 위해 try-catch 문과 commit, rollback의 코드가 추가되어야 했습니다. (아래 코드와 같은)

```java
try {
    con.setAutoCommit(false);
    con.commit();
} catch (SQLException e) {
    con.rollback();
    throw e;
}
```

이런 방식으로 트랜잭션 관리를 하는 방법 이외에 다른 방법이 있을까요?

2019-10-17 08:30 UTC, jeonghoon1107 requested changes
안녕하세요 마틴!
구현 잘하셨네요 💯 
몇가지 피드백 남겼으니 확인부탁드려요 :)

말씀해주신 두 가지 방식 모두 좋지만 1번 방식이 사용성이 좀 더 좋아보이네요!

트랜잭션에 관련한 것은 미션 중 하나에 있는 것으로 알고 있어요!

2019-10-17 08:30 UTC, jeonghoon1107 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> T queryForObject(String query, Class<?> clazz, Object... objects) {
타입을 보장하지 못해서 런타임시 에러가 발생할 것 같은데 Class< T> 로 변경해보는 것은 어떨까요?

```
User user = jdbcTemplate.queryForObject(
                "SELECT userId, password, name, email FROM USERS WHERE userid=?",
                UserCreatedDto.class,
                userId);
```

2019-10-17 08:30 UTC, jeonghoon1107 commented on slipp/src/test/java/slipp/dao/UserDaoTest.java
> -    public void crud() throws Exception {
예외 케이스까지 테스트해보면 더 좋을 것 같아요!

2019-10-17 15:48 UTC, oeeen commented on slipp/src/test/java/slipp/dao/UserDaoTest.java
> -    public void crud() throws Exception {
Create, Read의 예외 케이스에 대해 테스트를 추가하였습니다!
Update는 다른 userId로 조회할 때 업데이트가 실패해야 하는데, 현재 유저 세션에 대한 검사 로직이 없어 업데이트가 실패하는 케이스가 없어 추가하지 않았습니다!

2019-10-18 14:46 UTC, jeonghoon1107 approved these changes
안녕하세요 마틴!
딱히 피드백 할 내용이 없네요 💯 
미션 진행하느라 고생 많으셨습니다 :)

2019-10-18 14:46 UTC, merged