[JDBC 라이브러리] 지노 미션 제출합니다.
woowacourse/jwp-jdbc pull request #24
Opened 2019-10-16 11:37 UTC by hyunssooo

안녕하세요 하비!
처음으로 리뷰 받는데 잘 부탁드립니다!

2019-10-16 23:17 UTC, young891221 requested changes
안녕하세요 지노! 리뷰어 하비입니다.
작성해 주신 부분에 더해서 몇 가지 개선 포인트를 남겨보았습니다.
확인해 보시고 답변이나 반영 부탁드립니다:)

2019-10-16 23:17 UTC, young891221 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +             ResultSet resultSet = preparedStatement.executeQuery()) {
SqlExcuteStrategy라는 인터페이스를 하나 더 받으면 어떨까요? 아래와 같이 처리하는

```java
ps -> {
                    ps.setString(1, user.getUserId());
                    ps.setString(2, user.getPassword());
                    ps.setString(3, user.getName());
                    ps.setString(4, user.getEmail());
                    ps.executeUpdate();
                }
```

2019-10-16 23:17 UTC, young891221 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (Connection connection = dataSource.getConnection();
`readForObject`, `readForList`를 하나로 합쳐보게끔 리펙토링 가능해 보입니다.
기본적인 템플릿 틀은 똑같아서요. 나머지는 RowMapper, SqlExcuteStrategy로 동적으로 할당 가능합니다.

2019-10-16 23:17 UTC, young891221 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public T readForObject(RowMapper<T> rowMapper, String sql, Object... values) {
반환값에 `Optional`이 들어가면 더 유용해 보이네요!

2019-10-16 23:17 UTC, young891221 commented on slipp/src/main/java/slipp/dao/UserDao.java
>  public class UserDao {
UserDao에 해당하는 테스트에 대한 변화는 없을까요??ㅎㅎ

2019-10-17 08:23 UTC, hyunssooo commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (Connection connection = dataSource.getConnection();
~~~java
T readForObject();
List<T> readForList();
~~~
이 부분은 고민했던 부분인데 List를 반환하는 메소드를 불러 object를 반환하는 메소드에서 .get(0)를 하는 생각을 해 봤습니다. 하지만 객체 하나만 반환해주는 메소드에서 while문을 돌면서 반복하는 행위 필요없다고 생각하여 두 메소드로 분리 했습니다. 혹시 더 좋은 방법이 있을까요??

2019-10-17 11:31 UTC, hyunssooo commented
안녕하세요 하비! 피드백 반영했습니다!
다른 의견 더 있으시면 부탁드릴게요!
낮에 질문 답변해주신거 감사합니다! :)

2019-10-17 15:20 UTC, young891221 approved these changes
멋진 리뷰 반영 감사합니다 지노!
더 이상 추가할 부분이 없어서 이만 머지하겠습니다. 고생하셨어요:)

2019-10-17 15:20 UTC, young891221 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (Connection connection = dataSource.getConnection();
그런식도 있겠군요.
개인적인 방식으로 저는 이렇게 풀었는데요. "SELECT"를 검색하는게 별로지만 이런식도 한번 참고해 보세요ㅎㅎ
https://github.com/young891221/jwp-jdbc/blob/d3385dd59f0a7f87064b2928820401b904beb8c4/src/main/java/next/dao/UserDao.java

2019-10-17 15:20 UTC, merged