[JDBC 라이브러리] 큰곰 미션 제출합니다.
woowacourse/jwp-jdbc pull request #26
Opened 2019-10-16 11:48 UTC by kunggom

최대한 포비의 강의에 맞춰 주어진 코드를 리팩토링해 보았습니다. 잘 부탁드립니다.

2019-10-17 09:38 UTC, byjo requested changes
큰곰 안녕하세요~ 이번 미션 리뷰를 맡은 브리입니다.
강의를 보고 리팩토링을 해보셨군요! 👍
몇 가지 개선하면 좋을 부분이 보여 피드백 드렸으니 확인 부탁드려요.
더 궁금하거나 이야기 나눠보고 싶으신 점 있다면 편하게 문의 주시구요! 😊

2019-10-17 09:38 UTC, byjo commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> List<T> findItems(final String sql, final RowMapper<T> mapper) {
여러 아이템을 요청할 때도 parameter를 받아야 하지 않을까요?  
예를 들어 아래와 같은 쿼리를 날리고 싶을 땐 어떻게 해야할까요?
```
  SELECT * FROM USERS WHERE name = "큰곰";
```

그리고 `findItem()` 메소드와 중복되는 코드를 줄일 수 있는 방법을 고민해보면 좋을 것 같아요.

2019-10-17 09:38 UTC, byjo commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        new JdbcTemplate().write(
혹시 요청마다 JdbcTemplate 객체를 새로 생성해야하는 이유가 있을까요?
그렇지 않다면 JdbcTemplate을 재사용 해보면 어떨까요?

2019-10-17 09:38 UTC, byjo commented on slipp/src/main/java/slipp/dao/UserDao.java
> +    public void update(final User user) {
UserDao를 서비스 코드에서 사용하도록 변경해보면 좋을 것 같아요.

2019-10-17 09:38 UTC, byjo commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (final Connection connection = ConnectionManager.getConnection();
`ConnectionManager`는 어플리케이션 패키지에 있는 서비스 코드로 보이네요.
`ConnectionManager`와 `JdbcTemplate` 간의 의존성 분리가 필요해보여요.

2019-10-17 09:38 UTC, byjo commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void write(final String sql, final Object... parameters) {
리팩토링 힌트를 참고해서 SQL문에 사용되는 값을 `PreparedStatementSetter` 를 통해 받는 것도 구현해보면 좋을 것 같아요.

2019-10-17 11:50 UTC, kunggom commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        new JdbcTemplate().write(
`UserDao`에서 `JdbcTemplate`를 한번 만들어 계속 재사용하도록 바꾸었습니다. 좋은 제안 감사합니다.

2019-10-17 11:51 UTC, kunggom commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (final Connection connection = ConnectionManager.getConnection();
`JdbcTemplate`을 생성할 때 커넥션 객체를 받도록 바꾸었습니다. `UserDao`의 생성자에서 `ConnectionManager.getConnection()`을 사용하도록 바꾸었는데, 커넥션 객체의 주입 위치가 이 정도면 괜찮을런지요?

2019-10-17 11:53 UTC, kunggom commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void write(final String sql, final Object... parameters) {
해당 클래스를 새로 만들고, 이를 주입받는 메소드 오버로딩을 하도록 하겠습니다.

2019-10-17 11:53 UTC, kunggom commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> List<T> findItems(final String sql, final RowMapper<T> mapper) {
여러 아이템에서의 파라미터 설정은 미처 생각하지 못했던 부분이네요. 적용하도록 하겠습니다.

2019-10-17 11:54 UTC, kunggom commented on slipp/src/main/java/slipp/dao/UserDao.java
> +    public void update(final User user) {
무슨 뜻인지 정확하게 이해하지 못했습니다. 다시 설명해 주시겠어요?

2019-10-17 12:12 UTC, kunggom commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (final Connection connection = ConnectionManager.getConnection();
> `UserDao`와 `ConnectionManager`는 같은 서비스 코드이므로 괜찮습니다.

빠른 답변 감사합니다. 이런 거 분리하려고 하면 고민되더라고요. 좋은 기준인 것 같습니다.

2019-10-17 12:13 UTC, kunggom commented on slipp/src/main/java/slipp/dao/UserDao.java
> +    public void update(final User user) {
>서비스로직(`Controller`)에서 `Database` 대신 `UserDao`를 사용하도록 변경하면 됩니다.

명쾌한 설명 감사합니다.

2019-10-17 12:40 UTC, kunggom commented on slipp/src/main/java/slipp/dao/UserDao.java
> +    public void update(final User user) {
지금 다시 생각해보니, 이번 미션의 목적은 `JdbcTemplate`을 만드는 것이므로 미리 주어진 `Controller`의 코드를 건드리는 것은 미션의 목적에서 벗어나는 게 아닐까 합니다.

2019-10-17 12:50 UTC, kunggom commented on slipp/src/main/java/slipp/dao/UserDao.java
> +    public void update(final User user) {
공통 피드백 확인했습니다.

2019-10-17 16:43 UTC, kunggom commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> List<T> findItems(final String sql, final RowMapper<T> mapper) {
중복 제거를 위해 내부적으로 이터레이터를 만들어 돌리도록 하였습니다.

2019-10-19 08:12 UTC, byjo approved these changes
피드백 드린 사항 반영하신 것 확인했습니다.
PR 머지할게요. 고생 많으셨습니다.

2019-10-19 08:12 UTC, byjo commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        this.jdbcTemplate = new JdbcTemplate(ConnectionManager.getDataSource());
지금까지 그리고 앞으로 진행할 미션들에서 프레임워크/라이브러리를 구현하는 것이 주가 되는데, 프레임워크/라이브러리 로직과 애플리케이션 코드를 분리해서 생각하는 연습을 해보면 좋을 것 같습니다.

2019-10-19 08:12 UTC, merged

2019-10-21 06:37 UTC, kunggom commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        this.jdbcTemplate = new JdbcTemplate(ConnectionManager.getDataSource());
좋은 의견 감사합니다. 고민하겠습니다.