[JDBC 라이브러리] 제이 미션 제출합니다.
woowacourse/jwp-jdbc pull request #27
Opened 2019-10-16 12:23 UTC by JunHoPark93

안녕하세요 영재님! 😀 리뷰이 제이입니다.
간단해 보였지만 쉽지 않은 미션이네요. 그래도 최대한 중복 제거를 해보았습니다. 
고민되는 점은 JdbcTemplate 내부의 "try 문에 대한 중복제거"까지를 어떻게 해야할지 입니다ㅠ
항상 감사드립니다! 😃

2019-10-16 23:40 UTC, young891221 requested changes
안녕하세요 제이! 리뷰어 하비입니다.
JdbcTemplate를 실제 사용하는 부분은 깔끔한데 실제 JdbcTemplate 내부는 
리펙토링 포인트가 보여 몇 가지 개선 포인트를 남겨보았습니다.
확인해 보시고 답변이나 반영 부탁드립니다:)

2019-10-16 23:40 UTC, young891221 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void executeUpdate(String sql, Object... args) {
SqlExcuteStrategy라는 인터페이스를 하나 더 받으면 어떨까요? 아래와 같이 처리하는

```java
ps -> {
                    ps.setString(1, user.getUserId());
                    ps.setString(2, user.getPassword());
                    ps.setString(3, user.getName());
                    ps.setString(4, user.getEmail());
                    ps.executeUpdate();
                }
```
현재는 동적으로 할당하지만 동적으로만 가능한 경우가 유한해 보입니다.

2019-10-16 23:40 UTC, young891221 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> T queryForObject(String sql, ResultSetMappingStrategy<T> strategy, Object... args) {
반환값에 Optional이 들어가면 더 유용해 보이네요!

2019-10-16 23:40 UTC, young891221 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> List<T> query(String sql, ResultSetMappingStrategy<T> strategy, Object... args) {
executeUpdate, query, queryForObject를 하나로 합쳐보게끔 리펙토링 가능해 보입니다.
기본적인 템플릿 틀은 똑같아서요. 나머지는 ResultSetMappingStrategy, SqlExcuteStrategy로 동적으로 할당 가능합니다.

2019-10-17 06:11 UTC, JunHoPark93 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void executeUpdate(String sql, Object... args) {
setter전략 인터페이스를 구현해보았습니다!

2019-10-17 06:11 UTC, JunHoPark93 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> List<T> query(String sql, ResultSetMappingStrategy<T> strategy, Object... args) {
오버로딩을 통해서 코드양을 줄여보았습니다!

2019-10-17 06:13 UTC, JunHoPark93 commented
빠른 리뷰 감사드립니다!
말씀 주신 부분들 반영해보았습니다. select, update, insert 를 합치는 방식이 잘 되지 않아 최대한 오버로딩으로 줄여보았습니다. 혹시 이렇게 해도 괜찮을지 궁금합니다!

2019-10-17 08:56 UTC, young891221 approved these changes
리뷰 반영 잘 해주셨네요. 제이! 💯 
추가로 코멘트 드릴 부분은 없어서 바로 머지하겠습니다!

2019-10-17 08:56 UTC, merged