[JDBC 라이브러리] 코맥 미션 제출합니다.
woowacourse/jwp-jdbc pull request #32
Opened 2019-10-17 07:28 UTC by CODEMCD

안녕하세요?
이번 미션을 통해 공통적인 로직을 추출하는 리펙토링 연습을 해보았습니다. 반환값만 다른 상황을 처리하기 위해 제네릭을 사용하였는데, 거의 처음 사용해봐서 많이 해맸던 것 같습니다.
부족한 부분이 많습니다. 
잘 부탁드립니다!

2019-10-17 16:22 UTC, kingbbode requested changes
안녕하세요!
코멘트 몇 가지 남겼습니다 :)
확인 부탁드려요.

2019-10-17 16:22 UTC, kingbbode commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            log.error(e.getMessage());
메시지 전달만으로 예외 추적이 가능할까요? Exception 상태를 보존해주면 좋을 것 같아요.

https://rules.sonarsource.com/java/tag/error-handling/RSPEC-1166

2019-10-17 16:22 UTC, kingbbode commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private PreparedStatementSetter createPreparedStatementSetter(Object... objects) {
PreparedStatementSetter 구현체 클래스를 작성해보는 것은 어떨까요?

2019-10-17 16:22 UTC, kingbbode commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +
같은 일을 하는 메서드들이 서로 완전히 분리되어 있네요.
메서드를 조합하여 중복을 제거해보면 좋을 듯 합니다.

2019-10-17 16:22 UTC, kingbbode commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            T result = null;
빈 껍데기가 존재할 필요가 있나요?
이러한 선언으로 인해 결과를 끝까지 보아야만 가독이 될 수 밖에 없어지는 것 같아요.
선언 없이 조금 더 빠른 반환을 즉시 해주어 사고의 흐름을 더 단순하게 해주는 것은 어떨까요.

2019-10-17 16:22 UTC, kingbbode commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcExecutor.java
> +public interface JdbcExecutor<T> {
이 인터페이스가 어떠한 결합을 낮추어주는지, 혹은 그럴 필요가 있는지 모르겠네요 :)
반드시 필요할까요?

2019-10-19 08:48 UTC, CODEMCD commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            log.error(e.getMessage());
피드백 감사합니다!

이번 피드백을 통해 Exception 출력하고 관리하는 것에 대해 조금 더 알게 되었습니다. 기존에는 단순히 예외가 발생했다는 것만 보여주면 끝인 줄 알았습니다. 하지만 단순히 `e.getMessage()`만 사용한 경우에는 실제로 예외가 발생한 stack trace를 보여주지 않기 때문에 디버깅하기가 매우 힘들다는 것을 알게 되었습니다. 이러한 변경에 따라 예외가 로그를 통해 콘솔에 출력되는 변화는 다음과 같았습니다.

1. `log.error(e.getMessage())` 경우

```
17:41:02.529 [ERROR] [main] [nextstep.jdbc.JdbcTemplate] - null
```

2. `log.error("Fail Update", e)` 경우

```
17:42:31.241 [ERROR] [main] [nextstep.jdbc.JdbcTemplate] - Fail Update
java.sql.SQLException: null
	at nextstep.jdbc.JdbcTemplate.update(JdbcTemplate.java:20)
	at slipp.dao.UserDao.insert(UserDao.java:17)
	at slipp.dao.UserDaoTest.crud(UserDaoTest.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	....
```

그리고 checked exception인 SQLException을 런타임 예외로 바꿔서 던지는 요구사항을 처리할 때 제가 만든 커스텀 런타임 예외 객체를 생성할 때 SQLException를 매개변수로 넘겨주어 보존하도록 하였습니다. 이러한 경우 어디서 SQLException이 발생했는지 아래와 같이 콘솔에 추가적으로 출력해주었습니다.

```
Caused by: java.sql.SQLException
	at nextstep.jdbc.JdbcTemplate.update(JdbcTemplate.java:20)
	... 65 more
```

2019-10-20 08:45 UTC, CODEMCD commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +
피드백 감사합니다!

매개변수가 다르지만 내부 로직이 완전히 같은 메서드들을 중복하여 구현하였습니다. 이를 한 메서드가 다른 메서드를 호출하도록 변경하였습니다. 가변인자는 결국 `PreparedStatementSetter`를 구현해야 하므로 이를 매개변수로 받는 메서드를 호출하도록 하였습니다.

2019-10-20 08:48 UTC, CODEMCD commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private PreparedStatementSetter createPreparedStatementSetter(Object... objects) {
피드백 감사합니다!

람다나 익명 클래스를 사용할 때는 한 번만 사용할 때 간편하기 위해서라고 생각합니다. 하지만 위 메서드는 여러 곳에서 호출을 하므로, 이는 구현체 클래스를 만드는 것이 좋겠다고 생각하게 되었습니다.

2019-10-20 08:52 UTC, CODEMCD commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            T result = null;
피드백 감사합니다!

생각해보니 변수를 전혀 사용할 필요가 없었습니다. 피드백해주신 방법대로 하는 것이 가독성이 좋아진다고 느끼게 되었습니다.

2019-10-21 16:10 UTC, CODEMCD commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcExecutor.java
> +public interface JdbcExecutor<T> {
피드백 감사합니다!

`JdbcExecutor`를 인터페이스로 분리한 이유는 반복되는 `try/catch`문을 하나의 메서드에서 처리하려고 했습니다. 그리고 각 쿼리를 담당하는 메서드에서 람다로 `JdbcExecutor`를 구현하는 형식으로 하였는데, 지금 보면 개인적으로 가독성이 많이 안좋아졌다고 생각합니다. 리뷰어님의 피드백을 받고 다시 이를 없애서 각각의 메서드에서 `try/catch`문으로 처리하도록 변경하였습니다.

2019-10-23 09:14 UTC, kingbbode commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            log.error(e.getMessage());
👍

2019-10-23 09:18 UTC, kingbbode approved these changes
안녕하세요 코맥!
피드백을 실행해보고 결과를 공유해주신 것 좋네요 :) 👍 
수고 많으셨습니다!

2019-10-23 09:18 UTC, kingbbode commented on slipp/src/main/java/slipp/dao/UserDao.java
> +            throw new NotFoundUserException();
데이터를 다루는 레이어에서 null 은 허용되는 것이 일반적이라고 생각합니다 :)
어플리케이션에서 처리하는 것이 어떨까요?

2019-10-23 09:18 UTC, merged