[JDBC 라이브러리] 유니 미션 제출합니다.
woowacourse/jwp-jdbc pull request #42
Opened 2019-10-18 11:22 UTC by yunheehyeon

2019-10-19 03:55 UTC, ssosso requested changes
안녕하세요, 유니~ 쏘쏘입니다:)
몇 가지 피드백 드리오니, 확인 부탁드립니다~
추가적으로 확인하고픈 부분을 아래와 같이 전달드립니다.
- ConnectionManager에서 설정부분만 slipp 모듈에 남기고 nextstep-jdbc로 옮겨와야 하지 않을까요~?

2019-10-19 03:55 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void update(String sql, PreparedStatementSetter setter) throws SQLException {
반환값이 있으면 어떨까요~?

2019-10-19 03:55 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> T queryForObject(String sql, PreparedStatementSetter setter, RowMapper<T> mapper) throws SQLException {
RuntimeException으로 변경하라는 요구사항이 있었는데 다시 한번 확인 부탁드립니다.

2019-10-19 03:55 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +                rs.close();
https://stackoverflow.com/a/43261594
PreparedStatement가 try-with-resources 문에 의해 자동으로 close되면 try문 안에 있는 ResultSet은 자동으로 close됩니다. 따라서 ResultSet을 try문으로 옮기고 finally문을 제거해도 좋습니다:)

2019-10-22 07:22 UTC, yunheehyeon commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void update(String sql, PreparedStatementSetter setter) throws SQLException {
update row의 개수를 반환하도록 변경했습니다.

2019-10-22 07:22 UTC, yunheehyeon commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public <T> T queryForObject(String sql, PreparedStatementSetter setter, RowMapper<T> mapper) throws SQLException {
반영했습니다!

2019-10-22 07:22 UTC, yunheehyeon commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +                rs.close();
반영했습니다!

2019-10-22 07:25 UTC, yunheehyeon commented
ConnectionManager를 nextstep-jdbc로 옮겨 설정부분을 properties에서 가져오도록 변경했습니다.

2019-10-22 15:15 UTC, ssosso requested changes
유니~ 피드백 하나 남겼습니다, 의견을 들려주세요:)

2019-10-22 15:15 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public JdbcTemplate(DataSource dataSource) {
ConnectionManager에서 connection을 생성해주는 getConnection 메서드가 있는데 여기서는 datasource를 주입받아 datasource에서 직접 getConnection하고 있네요, ConnectionManager를 주입받아 manager가 제공하는 getConnection메서드를 사용할지 지금처럼 유지할지 한번 고민해볼 필요가 있어 보입니다:)

2019-10-23 06:20 UTC, yunheehyeon commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public JdbcTemplate(DataSource dataSource) {
ConnectionManager의 getConnection메서드를 사용하는 것이 클래스 이름에도 적합하고 DataSource 를 관리하기 좋을 거 같습니다. 
기존 getConnection에서 DataSource를 다시 생성하는 부분을 변경했습니다.

2019-10-23 06:24 UTC, ssosso approved these changes
유니, 적용해주신 부분 확인하였습니다:)
고생 많으셨습니다:)~

2019-10-23 06:24 UTC, merged