[JDBC 라이브러리] 올레 미션 제출합니다.
woowacourse/jwp-jdbc pull request #44
Opened 2019-10-18 12:06 UTC by jinwookh

2019-10-19 04:00 UTC, ssosso requested changes
안녕하세요, 올레~ 쏘쏘입니다:)
몇 가지 피드백 드리오니 확인 부탁드립니다:)

2019-10-19 04:00 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/ConnectionManager.java
> +    private static final String DB_PW = "";
설정부분은 slipp모듈에 있어야 할 것 같은데 어떻게 생각하시나요~?

2019-10-19 04:00 UTC, ssosso commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        parameters.add(userId);
ParameterSetter도 resultMapper처럼 인자로 넘겨주는 건 어떨까요~?

2019-10-19 22:53 UTC, jinwookh commented on nextstep-jdbc/src/main/java/nextstep/jdbc/ConnectionManager.java
> +    private static final String DB_PW = "";
그래야 할 것 같습니다! 설정 부분을 slipp에서 하고, jdbcTemplate은 slipp 모듈에서 생성한 datasource를 주입받아 활용할 수 있도록 수정했습니다.
``` java
public class JdbcTemplate {
    private final DataSource dataSource;

    public JdbcTemplate(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    private Connection getConnection() {
        try {
            return dataSource.getConnection();
        } catch (SQLException e) {
            throw new IllegalStateException(e);
        }
    }
```

2019-10-19 23:27 UTC, jinwookh commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        parameters.add(userId);
넵 피드백 반영하기 위해 다음과 같이 수정했습니다.
``` java
public interface ParameterSetter {
    List set(Object... parameters);
}
```
```java
    public void executeQuery(String sql, ParameterSetter parameterSetter, Object... parameters) {
        try (Connection con = getConnection();
             PreparedStatement pstmt = con.prepareStatement(sql)) {
            executePreparedStatement(pstmt, parameterSetter.set(parameters));
        } catch (SQLException e) {
            throw new DatabaseException();
        }
    }
```

``` java
public void update(User user) {
        String sql = "UPDATE USERS " +
                "SET password=?, name=?, email=? " +
                "WHERE userId=?";

        jdbcTemplate.executeQuery(sql, (Object... objects) -> {
            List<Object> parameters = new ArrayList<>(Arrays.asList(objects));
            return parameters;
        }, user.getPassword(), user.getName(), user.getEmail(), user.getUserId());
    }
```

jdbcTemplate에서 parameterSetter interface와 parameter들을 매개변수로 받습니다. parameterSetter는 parameter들을 리스트 형태로 합치는 역할을 합니다.

하지만, 이 방식을 사용해서 얻는 이점을 잘 모르겠습니다.
어떤 장점이 있는지 혹시 설명해 주실 수 있을까요?
또한 제가 이해를 잘못한 부분이 있다면, 말씀해 주시면 감사하겠습니다.

2019-10-20 12:19 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/ConnectionManager.java
> +    private static final String DB_PW = "";
설정 분리는 가능해졌네요:) 
다만, ConnectionManager의 역할이 datasource를 만들어주는 역할로 변하였네요, ConnectionManager라는 객체의 역할은 지금까지 datasource를 관리하고 Connection을 만들어주는 역할이었는데요, 현재는 JdbcTemplate이 datasource를 관리하고 직접 connection을 생성해내는 역할을 하고 있네요:)
답이 있어서 말씀드리는 것은 아니니 각 객체의 역할에 대해서 한번 생각해보시면 좋을 거 같아요:)
라이브러리를 사용하는 사람 입장에서도 datasource를 라이브러리에 넘겨주어야 되는 것인데 이것 또한 답이 있는 것은 아니지만, 좋은 방향이 더 있을지 생각해 볼 만한 좋은 부분이네요:)

2019-10-20 12:30 UTC, ssosso commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        parameters.add(userId);
아하~ 정확하게 말해서 PreparedStatementSetter라는 것을 제안했던 거였어요:)
하지만.. 지금 다시 생각해보니 올레 스타일도 좋네요:) setter를 받는 것보다는 파라미터를 보내는 스타일도 있을 수 있다는 생각이 듭니다. 한 가지 길만 있는 건 아니니까요~
피드백 반영을 적극적으로 고려해주신 점 감사드립니다, 제가 말씀드린 PreparedStatementSetter는 다른 크루들이 대부분 선택하는 스타일이니 다른 크루들의 코드를 한번 참고하시면 좋을 것 같습니다:) 올레는 제 피드백으로 인해 번거로우셨겠지만.. 이전 스타일로 돌아가도 좋을 것 같아요, 감사드립니다:)

2019-10-20 12:33 UTC, ssosso requested changes
올레, 피드백을 적극적으로 수용해주시려고 한 점 정말 깊이 감사드려요 :)
올레의 고민과 함께 하다보니 올레의 이전 방향이 더 좋다는 생각이 든 부분이 있어 코멘트하였습니다.
또한 객체의 역할에 대해 고찰해 볼 수 있는 부분도 코멘트로 남겨두었습니다.
현재도 충분하다고 생각이 들어 approve하오니 더 진행할 부분이 있으시면 다시 한번 리뷰요청 주시고, 아니면 merge요청 부탁드립니다:)

2019-10-20 12:34 UTC, ssosso approved these changes

2019-10-21 05:56 UTC, jinwookh commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        parameters.add(userId);
다른 크루들의 코드를 읽었습니다. 
PreparedStatementSetter 객체는 preparedStatement를 매개변수로 받아, preparedStatement를 set합니다.
```java
public interface PreparedStatementSetter {
    void setValues(PreparedStatement pstmt) throws SQLException;
}
```
이 방식을 사용하면 사용자가 직접 preparedStatement 객체를 조작할 수 있어 자유도가 높아집니다. 이 방식을 사용하지 않고 사용자가 List<Object> 형태로 parameter들을 관리하게 하면, 사용자가 굳이 preparedStatement 객체를 몰라도 된다는 장점이 있습니다.

List<Object> 형태로  parameter들을 관리하는 것이 낫다고 생각하여, 이전 스타일로 돌아갔습니다!

2019-10-21 13:35 UTC, jinwookh commented on nextstep-jdbc/src/main/java/nextstep/jdbc/ConnectionManager.java
> +    private static final String DB_PW = "";
쏘쏘님 말을 듣고 보니, JdbcTemplate 객체가 Connection을 생성하는 역할을 하기에는 너무 많은 역할을 맡은 것 같아요. JdbcTemplate 객체가 Connection 객체를 주입받도록 코드를 수정했습니다.
```java
    public JdbcTemplate(Connection connection) {
        this.connection = connection;
    }
```
이렇게 코드를 수정하니, userDao의 메서드마다 jdbcTemplate 객체를 만드는 코드가 존재한다는 단점이 있었어요. 
```java
JdbcTemplate jdbcTemplate = new JdbcTemplate(ConnectionManager.getConnection());
```
더 좋은 구현 방법에 대해 피드백 남겨주시면 감사하겠습니다!

2019-10-21 14:20 UTC, ssosso commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        parameters.add(userId);
good!

2019-10-21 14:32 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/ConnectionManager.java
> +    private static final String DB_PW = "";
- Connection을 생성하는 로직 백단을 계속 타고 들어가보면 계속해서 새로운 Connection을 생성합니다. 따라서 JdbcTemplate을 생성할 때 Connection을 주입해주는 것은 하나의 Connection만 사용하게 됩니다. 여러 쓰레드가 JdbcTemlate에 접근하게 되고 Connection객체를 공유하기 때문에 이는 잘못되었다고 할 수 있습니다. Connection은 select, update 등의 단위로 생성해서 사용해야 합니다. Connection을 주입하는 방식이 아닌 다른 방식을 생각해 보아야 합니다:)
- jdbcTemplate은 올레가 생각하신 것처럼 여러번 생성할 필요가 없는 객체입니다. 따라서 프로그램 상 하나만 생성해두고 이를 Dao에 주입해주면 좋습니다. 그러나 그렇게 하려면 통상 Spring에서 Bean을 생성하고 이를 주입해주는 방식과 비슷하게 구현해야 합니다. 이는 그렇게 어려운 개념은 아니나 해당 과제의 범위를 벗어난다고 생각하여 제안만 드리오니, 과제 성격을 고려하여 진행해주세요:)

2019-10-21 14:36 UTC, ssosso requested changes
올레~ 변경한 사항에서 수정되어야 할 부분이 있어요~
댓글 달았는데 한번 확인해주실 수 있을까요~?
올레가 질문주신 부분에 대해서도 답변 달았습니다:)

2019-10-22 04:14 UTC, jinwookh commented on nextstep-jdbc/src/main/java/nextstep/jdbc/ConnectionManager.java
> +    private static final String DB_PW = "";
자세한 설명 감사합니다. datasource를 주입받는 형식으로 다시 되돌렸습니다!

2019-10-22 15:09 UTC, ssosso commented on nextstep-jdbc/src/main/java/nextstep/jdbc/ConnectionManager.java
> +    private static final String DB_PW = "";
ConnectionManager를 주입받는 방식은 어떨까요~?

2019-10-22 15:10 UTC, ssosso approved these changes
생각보다 리뷰가 길어지고 있네요, datasource는 올레가 느낀 것처럼 jdbcTemplate이 하는 역할이 하나 더 생기는 것이라 다른 피드백을 남겼어요:) 하지만 approve하고 merge하오니 혹시 변경하고자 한다면 다시 리뷰요청 주세요:)

2019-10-22 15:10 UTC, merged