[대용량 데이터 처리] 철시 미션 제출합니다.
woowacourse/jwp-jdbc pull request #67
Opened 2019-11-11 06:11 UTC by pkch93

인덱스 생성 및 정규화 테이블 생성, 데이터 삽입 관련 sql문은 test/resources/ddl.sql에 있습니다.

감사합니다 :)

2019-11-11 14:47 UTC, woowahanCU commented on study/src/test/java/sql/QueryTest.java
> +        String normalizedTable = "DEV_DATA";
이 테이블 생성 쿼리도 같이 올려주시겠어요? ㅎ;

2019-11-11 14:48 UTC, woowahanCU commented on study/src/test/java/sql/QueryTest.java
> +        jdbcTemplate = new JdbcTemplate(ConnectionManager.getDataSource());
다른 사용자도 사용할 수 있게 하려면 좀 더 범용성이 좋아야 하지 않을까요

2019-11-11 14:49 UTC, woowahanCU requested changes
scheme SQL문도 같이 공유 부탁드려요 ~ :)

2019-11-14 08:03 UTC, pkch93 commented
stduy/src/test/resources 폴더 안에 정규화에 사용한 scheme.sql을 추가했습니다!

2019-11-18 07:58 UTC, merged