[JDBC 라이브러리] 닉 미션 제출합니다.
woowacourse/jwp-jdbc pull request #8
Opened 2019-10-15 08:42 UTC by wbluke

안녕하세요 리뷰이 닉입니다ㅎㅎ
이번 미션 잘 부탁드립니다 :)

2019-10-16 00:30 UTC, jeonghoon1107 requested changes
안녕하세요 닉!
깔끔하게 구현 잘하셨네요 💯 
아쉬운 부분이 있어 간단한 피드백 남겼어요!
확인부탁드려요 :)

2019-10-16 00:30 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/dao/UserDao.java
> +            while (rs.next()) {
findAll 메서드와 findByUserId 메서드에서 rs.next()를 확인하는 작업을 합칠 수 있을 것 같은데, JdbcTemplate안에 구현해보면 어떨까요?

2019-10-16 00:30 UTC, jeonghoon1107 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            throw new ExecuteUpdateFailedException(e);
exception이 발생했을 때 추가적으로 로그를 남기면 원인을 추적하기 더 좋지 않을까요?

2019-10-16 00:30 UTC, jeonghoon1107 commented on nextstep-jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> +public interface RowMapper<T> {
💯

2019-10-16 00:30 UTC, jeonghoon1107 commented on slipp/src/test/java/slipp/dao/UserDaoTest.java
>  import org.junit.jupiter.api.BeforeEach;
예외 상황에 대한 테스트가 추가되면 더 좋을 것 같아요!

2019-10-16 05:03 UTC, wbluke commented
리뷰 감사합니다! 다음과 같이 수정하였습니다 :)
다시 한번 리뷰 부탁드립니다ㅎㅎ

**1. RowMapper 책임 분리**
RowMapper에서 rs.next()를 하면서 반복문을 돌던 관심사를 JdbcTemplate으로 넘겼습니다. 그랬더니 RowMapper 자체도 이름에 알맞게 하나의 Row에 대해서만 mapping하는 책임만 가지고 있고, Template 쪽에서도 RowMapper의 메소드 자체를 반복하면서 일관성있게 처리할 수 있었습니다.
다만 기존 로직에서는 RowMapper의 제네릭 타입에 따라 JdbcTemplate.executeQuery()의 반환형이 결정되다 보니, 수정하면서는 findUserById와 findAll 모두 List<T>를 반환하도록 수정하였습니다. 

**2. log 추가 및 test 추가**
로그와 테스트를 빼먹지 않는 것은 정말 습관이 중요한 것 같습니다ㅜㅜ 실력이 올라갈수록 더욱더 꼼꼼하게 챙기도록 하겠습니다...!

**3. UserDao 수정 및 Controller 수정**
UserDao를 LazyHolder를 사용한 싱글톤으로 변경하고, 기존 Controller의 DataBase 사용 로직들을 전부 UserDao를 사용하도록 수정하였습니다!

2019-10-16 12:12 UTC, jeonghoon1107 requested changes
안녕하세요 닉!
마지막으로 피드백 한가지 남겼습니다!
확인부탁드려요 :)

2019-10-16 12:12 UTC, jeonghoon1107 commented on slipp/src/main/java/slipp/dao/UserDao.java
> +        List<User> users = jdbcTemplate.executeQuery(sql, rowMapper, userId);
프레임워크인 만큼 사용성을 조금 더 생각해보면 어떨까요!?
무조건 List를 리턴하여 애플리케이션에서 하나를 꺼내오지 않고 JdbcTemplate안에서 해결되면 좋을 것 같아요!

2019-10-16 13:12 UTC, wbluke commented
리뷰 반영하였습니다! :)
RowMapper의 제네릭 T를 받아서 T를 반환하는 메소드와 List<T>를 반환하는 메소드 사이에서
오버로딩을 사용하고 싶었는데, 파라미터를 유지할 수 밖에 없는 것 같아서 다른 메소드 이름을 사용하였습니다.

2019-10-17 09:07 UTC, jeonghoon1107 approved these changes
안녕하세요 닉!
피드백 반영까지 잘 해주셨네요 👍 
고생많으셨습니다 :)
추가적으로 궁금하신 점은 DM주세요!

2019-10-17 09:08 UTC, merged